### ISSUE TITLE
Duplicate alleles produced

### ISSUE THREAD

**Issue by Marcel-Mueck** [endast/fake-vcf#243]
## 🐛 Bug Report

when creating a fake vcf file from a previously created reference, some rows contain duplicates in the ref/alt allele columns (i.e. ref and alt alleles match for some row in the vcf), this causes issues when normalizing the data using `bcftools norm`

## 🔬 How To Reproduce

1. create a reference using a fasta file: `poetry run fake-vcf import-reference fasta/GRCh38.primary_assembly.genome.fa reference/`
2. create fake vcf file from reference: `poetry run fake-vcf generate --reference-dir-path reference/ --chromosome chr1 --num_rows 12000 --num_samples 10000 --fake_vcf_path vcf/chr1test.vcf.gz  `
3. run `bcftools norm -m-both -f fasta/GRCh38.primary_assembly.genome.fa vcf/chr1test.vcf.gz `

**Comment by endast** [comment]
Fixed in #246
